# Generated by Django 5.1.3 on 2024-11-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_rename_pharmcompany_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'модуль', 'verbose_name_plural': 'модули'},
        ),
    ]
